import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import Web3ModalProvider from "./Web3Modal";
import LensProvider from "./LensProvider";
import PrivyProvider from "./PrivyProvider";
import { Nav } from "./_components/nav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <Web3ModalProvider>
            <PrivyProvider>
              <LensProvider>
                <Nav />
                {children}
              </LensProvider>
            </PrivyProvider>
          </Web3ModalProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
